# Generated by Django 2.2.4 on 2019-09-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Cycle', models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'College'), ('Lycee', 'Lycee'), ('Université', 'Université')], default='Not selected', max_length=200)),
                ('Type', models.CharField(choices=[('Public', 'Public'), ('Privé', 'Privé')], default='Not selected', max_length=200)),
                ('Adress', models.CharField(default='Taroudant', max_length=200)),
                ('Effectif_total', models.IntegerField(default=0, null=True)),
                ('Nombre_Enseignant', models.IntegerField(default=0, null=True)),
                ('Superficie', models.IntegerField(default=0, null=True)),
                ('Latitude', models.FloatField(default=30, max_length=8)),
                ('Longitude', models.FloatField(default=-8, max_length=8)),
            ],
        ),
    ]
