# Generated by Django 2.2.4 on 2019-09-12 02:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('taroudant_etabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='etablissements',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
